Add files via upload
LacteaVia322/-MMAD pull request #9
Opened 2020-11-30 13:19 UTC by nookhi

2020-12-01 09:16 UTC, LacteaVia322 commented on parser2.py
> +    return r
Можно сразу записать в return все чему равно переменная r.
return requests.get('https://auto.ru/cars/ferrari/all/')

2020-12-01 09:17 UTC, LacteaVia322 commented on parser2.py
> +parse()
Зачем выделять это как отдельную функцию, если можно его записать телом класса.

2020-12-07 05:46 UTC, stanislavlyalin requested changes

2020-12-07 05:46 UTC, stanislavlyalin commented on parser2.py
> +    carsQuantity = 0
Я так понимаю, `carsQuantity` - это количество элементов в списке `items`? Можно не вводить дополнительную переменную, а просто взять `len(items)`

2020-12-07 05:46 UTC, stanislavlyalin commented on parser2.py
> +    return cars
Функция возвращает словарь `cars`. Лучше вывод на экран убрать из функции и переместить его наружу, чтобы не смешивать ответственности. Или можно добавить функцию вывода на экран, которая будет принимать сформированный в `get_content` словарь

2020-12-09 04:30 UTC, merged